apiVersion: v1
kind: ConfigMap
metadata:
  name: pedidos-veloz-config
  namespace: pedidos-veloz
  labels:
    app.kubernetes.io/name: pedidos-veloz
data:
  # Configurações do banco de dados
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "pedidos_veloz"
  DB_USER: "pedidos_user"

  # URLs dos serviços internos
  ORDERS_SERVICE_URL: "http://orders-service:3001"
  PAYMENTS_SERVICE_URL: "http://payments-service:3002"
  INVENTORY_SERVICE_URL: "http://inventory-service:3003"

  # Ambiente
  NODE_ENV: "production"
